'use strict';
const DB='ielts-reading-package-v1',STORE='files',META='meta';
self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
function read(path){return new Promise(ok=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>{const d=r.result,q=d.transaction(STORE).objectStore(STORE).get(path);q.onsuccess=()=>{d.close();ok(q.result)};q.onerror=()=>{d.close();ok(null)}};r.onerror=()=>ok(null)})}
function meta(){return new Promise(ok=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>{const d=r.result;if(!d.objectStoreNames.contains(META)){d.close();return ok(null)}const q=d.transaction(META).objectStore(META).get('package');q.onsuccess=()=>{d.close();ok(q.result)};q.onerror=()=>{d.close();ok(null)}};r.onerror=()=>ok(null)})}
const mime=p=>({html:'text/html; charset=utf-8',htm:'text/html; charset=utf-8',js:'text/javascript; charset=utf-8',css:'text/css; charset=utf-8',json:'application/json; charset=utf-8',pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',svg:'image/svg+xml',webp:'image/webp',mp3:'audio/mpeg',wav:'audio/wav',woff:'font/woff',woff2:'font/woff2'}[p.split('.').pop().toLowerCase()]||'application/octet-stream');
async function fromDirectory(path){const m=await meta();if(m?.mode!=='directory'||!m.handle)return null;try{let dir=m.handle;const parts=path.split('/').filter(Boolean),name=parts.pop();for(const part of parts)dir=await dir.getDirectoryHandle(part);const handle=await dir.getFileHandle(name);return await handle.getFile()}catch(_){return null}}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url),mark='/reading-local/';if(!u.pathname.includes(mark))return;e.respondWith((async()=>{let path=decodeURIComponent(u.pathname.split(mark)[1]||'index.html');if(!path||path.endsWith('/'))path+='index.html';const row=await read(path),blob=row?.blob||await fromDirectory(path);if(blob)return new Response(blob,{headers:{'Content-Type':blob.type||mime(path),'Cache-Control':'no-store'}});return new Response('阅读题库文件不存在：'+path+'。如果移动过题库文件夹，请返回 IELTS 面板重新连接。',{status:404,headers:{'Content-Type':'text/plain; charset=utf-8'}})})())});
